In [2]:
#seriesReaderWriter01.py

#stpe01
import pandas as pd

myindex = ['서울', '부산', '광주', '대구', '울산', '목포', '여수']
mylist = [50, 60, 40, 80, 70, 30, 20]
myseries = pd.Series(data=mylist, index=myindex)
print(myseries)

#step02
print('\n색인의 이름으로 값 읽기')
print(myseries[['대구']])

print('\n라벨 이름이로 슬라이싱')
print(myseries['대구':'목포'])

#step03
print('\n여러 개의 색인 이름으로 데이터 읽기')
print(myseries[['대구', '여수']])

print('\n정수릉 이용한 데이터 읽기')
print(myseries[[2]])

#step04
print('\n0, 2, 4번째 데이터 읽기')
print(myseries[0:5:2])

#step05
myseries[2] = 22
myseries[2:5] = 33
myseries[['서울', '대구']] = 55
myseries[0::2] = 77

print(myseries)

서울    50
부산    60
광주    40
대구    80
울산    70
목포    30
여수    20
dtype: int64

색인의 이름으로 값 읽기
대구    80
dtype: int64

라벨 이름이로 슬라이싱
대구    80
울산    70
목포    30
dtype: int64

여러 개의 색인 이름으로 데이터 읽기
대구    80
여수    20
dtype: int64

정수릉 이용한 데이터 읽기
광주    40
dtype: int64

0, 2, 4번째 데이터 읽기
서울    50
광주    40
울산    70
dtype: int64
서울    77
부산    60
광주    77
대구    55
울산    77
목포    30
여수    77
dtype: int64

In [2]:
#2.3 데이터 프레임
import pandas as pd

sdata = {'city': ['서울', '서울', '서울', '부산', '부산'], \
         'year': [2000, 2001, 2002, 2001, 2002], \
         'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

mycolumn = ['city', 'year', 'pop']
myindex = ['one', 'two', 'three', 'four', 'five']
myframe = pd.DataFrame( sdata, columns=mycolumn, index=myindex)
print(myframe)

      city  year  pop
one     서울  2000  1.5
two     서울  2001  1.7
three   서울  2002  3.6
four    부산  2001  2.4
five    부산  2002  2.9

In [21]:
import numpy as np
import pandas as pd

myindex = ['이순신', '김유신', '강감찬', '광해군', '연산군']
mycolumns = ['서울', '부산', '광주', '목포', '경주']
mylist = list( 10 * onedata for onedata in range(1, 26))
print(mylist)
print()

myframe = pd.DataFrame(np.reshape(mylist, (5,5)), index=myindex, columns=mycolumns)
print(myframe)
print()

print('\n#1 행만 Series로 읽어 오기')
result = myframe.iloc[1]
print(type(result))
print(result)
print()

print('\n#몇개의 행만 Series로 읽어 오기')
result = myframe.iloc[[1,3]]
print(type(result))
print(result)
print()

print('\n#짝수의 행만 Series로 읽어 오기')
result = myframe.iloc[0::2]
print(result)
print()

print('\n#이순 행만  Dataframe로 읽어 오기')
result = myframe.loc['이순신']
print(type(result))
print(result)
print()

print(myframe.index)
print('-'*40)

mytarget = np.random.choice(myframe.index, 3)
print(mytarget)

result = myframe.loc[['강감찬'], ['광주']]
print(result)

result = myframe.loc[myframe['부산'] <= 100]
print(result)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250]

      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
김유신   60   70   80   90  100
강감찬  110  120  130  140  150
광해군  160  170  180  190  200
연산군  210  220  230  240  250


#1 행만 Series로 읽어 오기
<class 'pandas.core.series.Series'>
서울     60
부산     70
광주     80
목포     90
경주    100
Name: 김유신, dtype: int64


#몇개의 행만 Series로 읽어 오기
<class 'pandas.core.frame.DataFrame'>
      서울   부산   광주   목포   경주
김유신   60   70   80   90  100
광해군  160  170  180  190  200


#짝수의 행만 Series로 읽어 오기
      서울   부산   광주   목포   경주
이순신   10   20   30   40   50
강감찬  110  120  130  140  150
연산군  210  220  230  240  250


#이순 행만  Dataframe로 읽어 오기
<class 'pandas.core.series.Series'>
서울    10
부산    20
광주    30
목포    40
경주    50
Name: 이순신, dtype: int64

Index(['이순신', '김유신', '강감찬', '광해군', '연산군'], dtype='object')
----------------------------------------
['강감찬' '김유신' '김유신']
      광주
강감찬  130
     서울  부산  광주  목포   경주
이순신  10  20  30  40   50
김유신  60  70  80  90  100